# Base runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj and restore 
COPY backend/*.csproj ./
RUN dotnet restore

# Copy rest of backend source
COPY Backend/. .

# Publishj optimized app
RUN dotnet publish -c Release -o /app/publish

# Final runtime image
FROM base as FINAL
WORKDIR /app
COPY --from=build /app/publish/ .
ENTRYPOINT ["dotnet". "Backend.csproj"]