name: Deploy Booking Project

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Stop old containers
        run: |
          cd /home/thoernve/booking-runner/actions-runner/_work/thoern-booking/thoern-booking
          docker-compose down || true

      - name: Build and start containers
        run: |
          cd /home/thoernve/booking-runner/actions-runner/_work/thoern-booking/thoern-booking
          docker-compose up -d --build

      - name: Cleanup old images
        run: docker image prune -af
